Final changes

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -5,8 +5,6 @@ on:
   - repository_dispatch
 
 permissions:
-  checks: write
-  actions: read
   contents: read
 
 jobs:
@@ -14,24 +12,28 @@ jobs:
     runs-on: ubuntu-latest
     if: github.actor != 'github-classroom[bot]'
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.11'
+    - name: Set up Python
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.11'
 
-      - name: Run unittest tests
-        run: |
-          python3 -m unittest discover -s tests -p "*.py" > test_results.txt || true
+    - name: Run unittest tests
+      id: run-test-cases
+      run: |
+        python3 -m unittest tests/test_fundamentals.py > failing_tests.txt || true
+        echo "result=$(cat failing_tests.txt)" >> $GITHUB_ENV
+      env:
+        GITHUB_ENV: $GITHUB_ENV
 
-      - name: Display test results
-        run: cat test_results.txt
+    - name: Display failing test(s)
+      run: cat failing_tests.txt
 
-      - name: Autograding Reporter
-        uses: classroom-resources/autograding-grading-reporter@v1
-        with:
-          runners: "run-test-cases"
-        env:
-          RUN-TEST-CASES_RESULTS: "${{steps.run-test-cases.outputs.result}}"
+    - name: Autograding Reporter
+      uses: classroom-resources/autograding-grading-reporter@v1
+      env:
+        RUN-TEST-CASES_RESULTS: "${{steps.run-test-cases.outputs.result}}"
+      with:
+        runners: run-test-cases
